ALTER TABLE "IntakeForm" ADD COLUMN IF NOT EXISTS "gpName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "IntakeForm" ADD COLUMN IF NOT EXISTS "gpPractice" TEXT NOT NULL DEFAULT '';
ALTER TABLE "IntakeForm" ADD COLUMN IF NOT EXISTS "gpPhone" TEXT NOT NULL DEFAULT '';
